import { campaignKey, campaignProgress, type Campaign } from "../../src/domain/campaigns";
import fs from "node:fs/promises";import path from "node:path";
export type FarmNode={id:string;campaign:string;campaignType:string;nodeNumber:number;energyCost:number;rate:number;materialId:string;unlocked:boolean};
export type Recipe={material:string;snowprintId:string;rarity:string;stat:string;craftable:boolean;recipe?:Array<{material:string;count:number}>};
type Battle={campaign:string;campaignType:string;nodeNumber:number;energyCost:number;rewards?:{potential?:Array<{id:string;effective_rate?:number}>;guaranteed?:Array<{id:string;min?:number;max?:number}>}};
export type Progress=Record<string,number>;export type ApiCampaign=Omit<Campaign,"id">;export type RankData=Record<string,Record<string,string[]>>;
export async function loadFarmingData(){try{const[b,r,u]=await Promise.all([fs.readFile(path.join(process.cwd(),"data/game/campaign-battles.json"),"utf8"),fs.readFile(path.join(process.cwd(),"data/game/upgrade-recipes.json"),"utf8"),fs.readFile(path.join(process.cwd(),"data/game/rank-up-data.json"),"utf8")]);return{battles:JSON.parse(b)as Record<string,Battle>,recipes:JSON.parse(r)as Record<string,Recipe>,rankData:JSON.parse(u)as RankData};}catch{return null;}}
export function progressFromReport(campaigns:Array<{name:string;type:string;highestUnlockedBattle:number|null}>):Progress{const out:Progress={};for(const c of campaigns){if(c.highestUnlockedBattle !== null)out[campaignKey(c.name,c.type)]=c.highestUnlockedBattle;}return out;}
function progressKey(b:Battle){return campaignKey(b.campaign,b.campaignType);}
export function progressFromApi(campaigns:ApiCampaign[]):Progress{const out:Progress={};for(const c of campaigns){const p=campaignProgress({...c,id:campaignKey(c.name,c.type)});if(p.highestUnlockedBattle!==null)out[campaignKey(c.name,c.type)]=p.highestUnlockedBattle;}return out;}
function unlocked(b:Battle,p:Progress){const max=p[progressKey(b)];return max===undefined?false:b.nodeNumber<=max;}
export function farmNodesFor(materialId:string,battles:Record<string,Battle>,progress:Progress):FarmNode[]{const out:FarmNode[]=[];for(const[id,b]of Object.entries(battles)){let rate=0;for(const reward of b.rewards?.guaranteed??[]){if(reward.id===materialId)rate+=(reward.min??1);}for(const reward of b.rewards?.potential??[]){if(reward.id===materialId)rate+=reward.effective_rate??0;}if(rate>0)out.push({id,campaign:b.campaign,campaignType:b.campaignType,nodeNumber:b.nodeNumber,energyCost:b.energyCost,rate,materialId,unlocked:unlocked(b,progress)});}return out.sort((a,b)=>Number(b.unlocked)-Number(a.unlocked)||(b.rate/b.energyCost)-(a.rate/a.energyCost));}
export function bestFarmNode(materialId:string,battles:Record<string,Battle>,progress:Progress){return farmNodesFor(materialId,battles,progress).find(x=>x.unlocked);}
export function nextRankMaterials(unitId:string,currentRank:number,rankData:RankData){const names=["Stone I","Stone II","Stone III","Iron I","Iron II","Iron III","Bronze I","Bronze II","Bronze III","Silver I","Silver II","Silver III","Gold I","Gold II","Gold III","Diamond I","Diamond II","Diamond III","Adamantine I","Adamantine II"];const key=names[currentRank];return key?(rankData[unitId]?.[key]??[]):[];}
export function expandMaterial(id:string,count:number,recipes:Record<string,Recipe>,out=new Map<string,number>()):Map<string,number>{const r=recipes[id];if(!r?.craftable){out.set(id,(out.get(id)??0)+count);return out;}for(const x of r.recipe??[])expandMaterial(x.material,count*x.count,recipes,out);return out;}
