const ICONS: Record<string,string> = {
  "Varro Tigurius": "VarroTigurius.webp",
  "Certus": "certus-removebg-preview.webp",
  "Bellator": "bellator.webp",
  "Incisus": "incisus-removebg-preview.webp",
  "Marneus Calgar": "marneus_calgar-removebg-preview.webp",
  "Titus": "titus.webp",
  "Makhotep": "Makhotep-removebg-preview.webp",
  "Imospekh": "Imospekh-removebg-preview.webp",
  "Aleph-Null": "Aleph-null.webp",
  "Thutmose": "Thutmose-removebg-preview.webp",
  "Anuphet": "Anuphet.webp",
  "Sibyll": "Sibyll-removebg-preview.webp",
  "Commissar Yarrick": "CommissarYarrick-removebg-preview.webp",
  "Kut Skoden": "Kutskoden-removebg-preview.webp",
  "Thaddeus Noble": "Thaddeusnoble-removebg-preview.webp",
  "Castellan Creed": "Castellancreed-removebg-preview.webp",
  "Angrax": "Angrax.webp",
  "Volk": "volk-removebg-preview.webp",
  "Archimatos": "archimatos.webp",
  "Haarken Worldclaimer": "HaarkenWorldclaimer-removebg-preview.webp",
  "Abaddon The Despoiler": "Abaddonthedespolier.webp",
  "Vindicta": "Vindicta-removebg-preview.webp",
  "Isabella": "Isabella-removebg-preview.webp",
  "Morvenn Vahl": "MorvennVahl-removebg-preview.webp",
  "Roswitha": "Roswitha-removebg-preview.webp",
  "Celestine": "Celestine-removebg-preview.webp",
  "Snotflogga": "snotflogga-removebg-preview.webp",
  "Gibbascrapz": "Gibbascrapz-removebg-preview.webp",
  "Snappawrecka": "Snappawrecka-removebg-preview.webp",
  "Tanksmasha": "Tanksmasha-removebg-preview.webp",
  "Boss Gulgortz": "BossGulgortz-removebg-preview.webp",
  "Sword Brother Godswyl": "sbg-removebg-preview.webp",
  "Brother Burchard": "brotherBurchard-removebg-preview.webp",
  "Ancient Thoread": "AncientThoread.webp",
  "Brother Jaeger": "brotherJaeger-removebg-preview.webp",
  "High Marshal Helbrecht": "HighMarshalHelbrecht-removebg-preview.webp",
  "Typhus": "Typhus-removebg-preview.webp",
  "Maladus": "Maladus-removebg-preview.webp",
  "Nauseous Rotbone": "Nauseousrotbone-removebg-preview.webp",
  "Pestillian": "Pestillian-removebg-preview.webp",
  "Corrodius": "Corrodius-removebg-preview.webp",
  "Calandis": "Calandis-removebg-preview.webp",
  "Aethana": "Aethana.webp",
  "Eldryon": "eldryon-removebg-preview.webp",
  "Maugan Ra": "Maugan_Ra-removebg-preview.webp",
  "Jain Zar": "Jain_Zar-removebg-preview.webp",
  "Sho'Syl": "sho_syl-removebg-preview.webp",
  "Re'Vas": "re_vas-removebg-preview.webp",
  "Darkstrider": "darkstrider-removebg-preview.webp",
  "Aun'Shi": "Aun-shi.webp",
  "Shadowsun": "ShadowSun.webp",
  "Ulf": "Ulf.webp",
  "Tjark": "Tjark.webp",
  "Arjac": "arjac.webp",
  "Njal Stormcaller": "Njal.webp",
  "Ragnar Blackmane": "Ragnar.webp",
  "Yazaghor": "Yazaghor.webp",
  "Toth": "toth.webp",
  "Abraxas": "Abraxas.webp",
  "Thaumachus": "Thaumachus-removebg-preview.webp",
  "Ahriman": "Ahriman.webp",
  "Azrael": "Azrael-removebg-preview.webp",
  "Sarquael": "Sarquael.webp",
  "Asmodai": "asmodai.webp",
  "Baraqiel": "baraqiel.webp",
  "Forcas": "forcas.webp",
  "Neurothrope": "Neurothrope-removebg-preview.webp",
  "Tyrant Guard": "TyrantGuard.webp",
  "Winged Tyrant Prime": "Winged_Prime.webp",
  "Deathleaper": "Deathleaper.webp",
  "PoM": "pom.webp",
  "Vitruvius": "vitruvius.webp",
  "Actus": "actus.webp",
  "Tan Gi'Da": "tanGida.webp",
  "Exitor-Rho": "exitor-rho.webp",
  "Sy-Gex": "sy-gex.webp",
  "Wrask": "wrask.webp",
  "Macer": "macer.webp",
  "Azkor": "azkor.webp",
  "Tarvakh": "tarvakh.webp",
  "Kharn": "kharn.webp",
  "Mataneo": "mataneo.webp",
  "Lucien": "lucien.webp",
  "Nicodemus": "nicodemus.webp",
  "Mephiston": "mephiston.webp",
  "Dante": "dante.webp",
  "Hollan": "hollan.webp",
  "Xybia": "xybia.webp",
  "Isaak": "isaak.webp",
  "Judh": "judh.webp",
  "Patermine": "patermine.webp",
  "Aesoth": "aesoth.webp",
  "Kariyan": "kariyan.webp",
  "Trajann": "trajann.webp",
  "Lucius": "lucius.webp",
  "Atlacoya": "atlacoya.webp"
};

function fallback(name:string){return name.slice(0,1).toUpperCase();}

export default function CharacterName({name,id}:{name:string;id?:string}){
  const icon=ICONS[name];
  const src=icon?`https://tacticusplanner.app/img/characters/${encodeURIComponent(icon)}`:null;
  return <span className="characterCell">
    {src?<img className="portrait" src={src} alt={name} loading="lazy" onError={(e)=>{e.currentTarget.style.display="none";}}/>:<span className="portrait fallback">{fallback(name)}</span>}
    <strong>{name}</strong>
  </span>;
}
