"use client";
import {useMemo,useState} from "react";
export type Column<T>={key:string;label:string;render:(row:T)=>React.ReactNode;sort?:(row:T)=>string|number;search?:(row:T)=>string};
export type Filter<T>={key:string;label:string;matches:(row:T)=>boolean};
export default function DataTable<T>({rows,columns,placeholder="Search…",filters=[]}:{rows:T[];columns:Column<T>[];placeholder?:string;filters?:Filter<T>[]}){
 const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");const [sortKey,setSortKey]=useState(columns[0]?.key??"");const [desc,setDesc]=useState(false);
 const counts=useMemo(()=>Object.fromEntries(filters.map(f=>[f.key,rows.filter(f.matches).length])),[rows,filters]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase(),active=filters.find(f=>f.key===filter);const filtered=rows.filter(r=>(!active||active.matches(r))&&(!q||columns.some(c=>(c.search?.(r)??String(c.sort?.(r)??"")).toLowerCase().includes(q))));const col=columns.find(c=>c.key===sortKey);if(!col?.sort)return filtered;return [...filtered].sort((a,b)=>{const av=col.sort!(a),bv=col.sort!(b);const n=typeof av==="number"&&typeof bv==="number"?av-bv:String(av).localeCompare(String(bv),undefined,{numeric:true});return desc?-n:n;});},[rows,columns,filters,query,filter,sortKey,desc]);
 function sort(key:string){if(sortKey===key)setDesc(v=>!v);else{setSortKey(key);setDesc(false);}}
 return <><div className="tableTools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/><span>{visible.length} of {rows.length}</span></div>{filters.length>0&&<div className="filterChips"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>All <b>{rows.length}</b></button>{filters.map(f=><button key={f.key} className={filter===f.key?"active":""} onClick={()=>setFilter(f.key)}>{f.label} <b>{counts[f.key]}</b></button>)}</div>}<div className="tableWrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.sort?<button className="sortButton" onClick={()=>sort(c.key)}>{c.label}{sortKey===c.key?(desc?" ↓":" ↑"):""}</button>:c.label}</th>)}</tr></thead><tbody>{visible.map((r,i)=><tr key={i}>{columns.map(c=><td key={c.key}>{c.render(r)}</td>)}</tr>)}</tbody></table></div></>;
}