import assert from "node:assert/strict";
import test from "node:test";
import {createElement} from "react";
import {JSDOM} from "jsdom";
import OrbPlanner from "../app/orbs/OrbPlanner";
import {rateCharacter} from "../src/domain/characterUtility";
import type {OrbCandidate} from "../src/domain/orbPlanner";
import type {ShopCatalog} from "../src/domain/shops";
import {WAR_PLAN_STORAGE_KEY} from "../src/domain/warBadgeTargets";
import shops from "../data/game/shops.json";

test("orb scopes restore War tiers, optional Mythic and full-goal budgets; source details show actionable shortages",async suite=>{
 const dom=new JSDOM("<!doctype html><html><body></body></html>",{url:"http://localhost/"});
 const descriptors=new Map<string,PropertyDescriptor|undefined>();
 for(const key of ["window","self","document","navigator","HTMLElement","Node","Event","MutationObserver","localStorage"]){descriptors.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{configurable:true,value:dom.window[key as keyof typeof dom.window]});}
 const {render,fireEvent,cleanup,act,within,waitFor}=await import("@testing-library/react");
 suite.after(async()=>{await act(async()=>{cleanup();});dom.window.close();for(const [key,descriptor] of descriptors){if(descriptor)Object.defineProperty(globalThis,key,descriptor);else Reflect.deleteProperty(globalThis,key);}});
 const make=(name:string,index:number,core=false):OrbCandidate=>({id:name,name,alliance:"Xenos",progressionIndex:index,rank:0,shards:0,mythicShards:0,campaignGoals:[],utility:rateCharacter({name,communityScore:3,accountPriority:80,mainRaidCore:core,mainRaidFlex:false,raidCore:false,raidFlex:false,warOption:false,incompleteCampaign:false})});
 const candidates=[make("Core",0,true),make("War",8),make("Wing",15,true)];
 const offenseTeams=[{name:"Gold offense",used:1,members:[{name:"War"}]}];
 dom.window.localStorage.setItem(WAR_PLAN_STORAGE_KEY,JSON.stringify({offense:["Gold offense"],offenseTiers:Array.from({length:10},()=>"gold")}));
 const view=render(createElement(OrbPlanner,{candidates,inventory:{Xenos:[{rarity:"Uncommon",amount:12},{rarity:"Rare",amount:20},{rarity:"Epic",amount:4}]},defenseTeams:[],offenseTeams,shops:shops as ShopCatalog}));
 fireEvent.click(view.getByRole("button",{name:/Longer-term orb plan/}));
 const rows=()=>within(view.getAllByRole("table")[1]!).getAllByRole("row");
 await waitFor(()=>assert.match(view.container.textContent!,/Active War Gold slot/));
 assert.equal(rows().length,3);assert.doesNotMatch(view.container.textContent!,/Mythic · 11 stars/);
 fireEvent.change(view.getByLabelText("Plan"),{target:{value:"goal"}});
 assert.match(rows()[1]!.textContent!,/460 regular shards total/);
 assert.match(rows()[1]!.textContent!,/10 Xenos Legendary/);
 fireEvent.change(view.getByLabelText("Include"),{target:{value:"war"}});
 assert.equal(rows().length,2);assert.match(rows()[1]!.textContent!,/War/);
 const sources=view.getByText("Get Xenos Epic orbs").closest("details")!;
 fireEvent.click(within(sources).getByText("Get Xenos Epic orbs"));
 assert.match(sources.textContent!,/3 draft orbs for 1,485 Guild Credits/);
 assert.match(sources.textContent!,/Cover 6 short with 2 pack\(s\): 2,970 Guild Credits/);
 assert.match(sources.textContent!,/spare lower orbs could make 4/);
 // Editing tiers changes the actual target; a Rare-capped offense does not need Epic.
 dom.window.localStorage.setItem(WAR_PLAN_STORAGE_KEY,JSON.stringify({offense:["Gold offense"],offenseTiers:Array.from({length:10},()=>"silver")}));
 fireEvent(window,new Event("storage"));
 await waitFor(()=>assert.match(view.container.textContent!,/No orb upgrades needed in this scope/));
 fireEvent.change(view.getByLabelText("Include"),{target:{value:"raid"}});
 fireEvent.click(view.getByLabelText("Include Mythic upgrades"));
 assert.match(view.container.textContent!,/20 Mythic shards/);
 assert.equal(rows().length,3);

 const extraStars={...make("Legendary extra stars",13),alliance:"Imperial",shards:250};
 const readyCandidates=[extraStars,{...make("Ready Imperial",8),alliance:"Imperial",shards:50},{...make("Other Imperial",8),alliance:"Imperial",shards:50},{...make("Ready Xenos",5),shards:20},{...make("Promote Chaos",7),alliance:"Chaos",shards:90},{...make("Blocked",8,true),alliance:"Imperial",shards:49}];
 const inventory={Imperial:[{rarity:"Epic",amount:12}],Xenos:[{rarity:"Rare",amount:10}],Chaos:[{rarity:"Epic",amount:0}]};
 view.rerender(createElement(OrbPlanner,{key:"ready-fixture",candidates:readyCandidates,inventory,defenseTeams:[],offenseTeams:[],shops:shops as ShopCatalog}));
 const readySection=within(view.getByRole("region",{name:"Shard-ready orb shopping list"}));
 const totals=within(readySection.getByRole("table",{name:"Shard-ready orb totals"}));
 assert.deepEqual(within(totals.getAllByRole("row")[1]!).getAllByRole("cell").slice(0,4).map(cell=>cell.textContent),["Imperial · Epic","12","20","8"]);
 assert.ok(readySection.getByText("IMPERIAL"));assert.ok(readySection.getByText("XENOS"));assert.ok(readySection.getByText("CHAOS"));
 fireEvent.click(view.getByLabelText("Include star upgrades within a rarity"));
 assert.ok(readySection.getByText("Legendary extra stars"));
 assert.match(readySection.getByRole("table",{name:"Shard-ready orb totals"}).textContent!,/Imperial · Legendary.*15/s);
 fireEvent.click(view.getByLabelText("Include star upgrades within a rarity"));
 assert.equal(readySection.queryByText("Legendary extra stars"),null);
 const queue=within(readySection.getByRole("table",{name:"Shard-ready character upgrades"}));
 assert.equal(queue.getAllByRole("row").length,5);
 assert.equal(queue.queryByText("Blocked"),null);
 assert.equal(queue.getAllByText("Ready to upgrade · check coins").length,2);
 assert.ok(queue.getByText("Collect 8 more orbs"));
 assert.ok(queue.getByText("Promote 1 time first"));
 assert.ok(queue.getAllByText("Ascend to Epic").length>=2);
 assert.match(totals.getAllByRole("row")[1]!.textContent!,/Guild Shop/);
 assert.doesNotMatch(totals.getAllByRole("row")[1]!.textContent!,/Blackstone/);
 fireEvent.click(readySection.getByRole("button",{name:/Shard-ready orb shopping list/}));
 assert.equal(readySection.queryByRole("table"),null);
 fireEvent.click(readySection.getByRole("button",{name:/Shard-ready orb shopping list/}));
 assert.equal(readySection.getAllByRole("table").length,2);
 assert.equal(view.getByRole("button",{name:/Longer-term orb plan/}).getAttribute("aria-expanded"),"false");
 view.rerender(createElement(OrbPlanner,{key:"synced-fixture",candidates:readyCandidates.map(row=>row.name==="Ready Imperial"?{...row,progressionIndex:9,shards:0}:row),inventory:{...inventory,Imperial:[{rarity:"Epic",amount:2}]},defenseTeams:[],offenseTeams:[],shops:shops as ShopCatalog}));
 const synced=within(view.getByRole("table",{name:"Shard-ready orb totals"}));
 assert.deepEqual(within(synced.getAllByRole("row")[1]!).getAllByRole("cell").slice(0,4).map(cell=>cell.textContent),["Imperial · Epic","2","10","8"]);
});
