"use client";
import { useState } from "react";
import Link from "next/link";
import CharacterName from "../components/CharacterName";
import { rankName } from "../../src/domain/ranks";
import { warGearLabel } from "../../src/domain/warGear";
import { uniqueWarTeamIndexes } from "../../src/domain/warTeams";
type Member={id:string;name:string;icon:string|undefined;rank:number|null;activeLevel:number|null;passiveLevel:number|null;items:Array<{slotId:string;rarity?:string;level:number;name?:string}>};type Team={name:string;used:number;wins:number;members:Member[];fieldable:boolean;missing:string[]};
const targets={gold:{label:"Gold I · 35 / 35",rank:12,ability:35},silver:{label:"Silver I · 26 / 26",rank:9,ability:26}} as const;
export default function WarDefensePlanner({teams,offenseTeams}:{teams:Team[];offenseTeams:Team[]}){
 const buildable=teams.filter(team=>team.fieldable);const[mode,setMode]=useState<"defense"|"offense">("defense"),[slots,setSlots]=useState(()=>uniqueWarTeamIndexes(buildable,5)),[open,setOpen]=useState<number|null>(null);const options=mode==="defense"?teams:offenseTeams;const assigned=slots.map(i=>buildable[i]).filter((x):x is Team=>!!x);const dup=assigned.flatMap(t=>t.members.map(m=>m.name)).filter((n,i,a)=>a.indexOf(n)!==i);
 const choose=(slot:number,choice:number)=>setSlots(current=>{const chosen=buildable[choice];if(!chosen)return current;const chosenNames=new Set(chosen.members.map(member=>member.name));const remainder=buildable.map((team,index)=>({team,index})).filter(({team,index})=>index!==choice&&!team.members.some(member=>chosenNames.has(member.name)));const picks=uniqueWarTeamIndexes(remainder.map(({team})=>team),4).map(index=>remainder[index]!.index);const next:number[]=[];let cursor=0;for(let index=0;index<5;index++)next.push(index===slot?choice:picks[cursor++]??current[index]??choice);return next;});
 const detail=(team:Team,target:keyof typeof targets)=><div className="tableWrap"><table><thead><tr><th>Character</th><th>Rank</th><th>Abilities</th><th>Gear</th></tr></thead><tbody>{team.members.map(m=>{const t=targets[target],r=Math.max(0,t.rank-(m.rank??0)),a=Math.max(0,t.ability-(m.activeLevel??0)),p=Math.max(0,t.ability-(m.passiveLevel??0)),gear=warGearLabel(m.items);return <tr key={m.id}><td><Link className="characterLink" href={`/characters/${m.id}`}><CharacterName name={m.name} id={m.id} icon={m.icon}/></Link></td><td className={r?"below":"ready"}>{m.rank===null?"Not owned":rankName(m.rank)}<small>{r?`+${r} → ${rankName(t.rank)}`:"Met"}</small></td><td className={a||p?"below":"ready"}>{m.activeLevel??"?"} / {m.passiveLevel??"?"}<small>{a||p?`+${a} active · +${p} passive`:"Met"}</small></td><td className={gear.ready?"ready":"below"}><strong>{gear.summary}</strong><small>{gear.detail}</small></td></tr>})}</tbody></table></div>;
 return <><div className="abilityViews warModeTabs"><button className={mode==="defense"?"active":""} onClick={()=>setMode("defense")}>Defense options</button><button className={mode==="offense"?"active":""} onClick={()=>setMode("offense")}>Offense options</button></div>{mode==="defense"?<section className="panel detailPanel"><div className="sectionTitle"><div><p className="eyebrow">YOUR FIVE DEFENSE SLOTS</p><h2>Select a team, then inspect it in place</h2><p className="sub">Slots 1–2 target Gold I / 35–35; slots 3–5 target Silver I / 26–26. Selecting a team automatically refills the other slots with the best distinct source teams.</p></div><div className="power">{new Set(dup).size?<strong className="below">{new Set(dup).size} conflicts</strong>:<strong className="ready">No conflicts</strong>}</div></div>{slots.map((choice,i)=>{const team=buildable[choice],target=i<2?"gold":"silver",conflicts=team?.members.filter(m=>dup.includes(m.name)).map(m=>m.name)??[];if(!team)return null;return <div className="campaignInvestmentGroup" key={i}><button className="campaignSectionToggle" onClick={()=>setOpen(open===i?null:i)}><div><p className="eyebrow">DEFENSE {i+1} · {targets[target].label}</p><h2>{team.name}</h2><p className={conflicts.length?"warSource below":"warSource"}>{conflicts.length?`Duplicate: ${conflicts.join(" · ")}`:"Distinct team"}</p></div><div className="campaignSectionStatus"><select value={choice} onClick={event=>event.stopPropagation()} onChange={event=>choose(i,Number(event.target.value))}>{buildable.map((option,index)=><option key={option.name} value={index}>{option.name}</option>)}</select><span className="campaignChevron">{open===i?"▴":"▾"}</span></div></button>{open===i?<div className="campaignSectionBody">{detail(team,target)}</div>:null}</div>})}</section>:null}<section className="panel detailPanel"><div className="sectionTitle"><div><p className="eyebrow">{mode.toUpperCase()} SOURCE OPTIONS</p><h2>Every supplied five-character lineup</h2></div><div className="power">{options.length}<strong> source rows</strong></div></div>{options.map((team,i)=><div className="campaignInvestmentGroup" key={team.name}><h3>{i+1}. {team.name} · {team.used.toLocaleString()} uses · {(team.wins/team.used*100).toFixed(1)}% win</h3><p className={team.fieldable?"warSource ready":"warSource below"}>{team.fieldable?"✓ Can build":"✕ Can’t build · missing " + team.missing.join(" · ")}</p></div>)}</section></>;
}
